plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'lk.disontech.campusassist'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "lk.disontech.campusassist"
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lint {
        abortOnError false
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation libs.fragment
    implementation(platform(libs.firebase.bom))
    implementation(libs.google.firebase.analytics)
    implementation libs.firebase.storage
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    implementation libs.payhere.android.sdk
    implementation libs.gson
    implementation libs.okhttp
    implementation "androidx.biometric:biometric:1.1.0"
    implementation "com.google.android.gms:play-services-maps:19.2.0"
    implementation "com.google.android.gms:play-services-location:21.3.0"
    implementation "com.jakewharton.threetenabp:threetenabp:1.4.4"
    implementation(platform(libs.firebase.bom)) // The "Master" version controller
    implementation(libs.firebase.messaging)
    implementation(libs.firebase.auth)
    implementation(libs.firebase.firestore)

}